### ISSUE TITLE
Tussosck range and value at 0

### ISSUE THREAD

**Issue by killyox** [WarmedxMints/OD-Explorer#9]
Hi, 1st thanks for 1.0.5, it solved the crash with tussocks in french version !
But there's still a little bug with it. As you can see on the screen, value and range are 0.

![OD Explorer](https://user-images.githubusercontent.com/3913411/213635942-c7118793-e8aa-4022-a097-33d220d2edcc.jpg)

Thanks for your help

**Comment by WarmedxMints** [comment]
That's intentional and not a bug.  The only way I have to look up values is via their English names. The non-localised name would be something like $Codex_Ent_Tussocks_04_Name and that is only reported via the ScanOrganic event.  I am yet to find a listing of all the values and the scan even isn't shared on EDDN so the only way for me to get the values would be to go out and scan every type myself which I, unfortunately, do not have the spare time to do. 

At this time, if you want all the values and colony ranges, playing in English is the only way.
